version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - aws cloudformation package --template-file upload-to-search.yaml --s3-bucket opensearch-artifacts-bkt --output-template-file upload.yaml

artifacts:  
  files:    
    - upload.yaml