AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with S3 trigger

Resources:

  uploadtosearch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 512
      Timeout: 900
      Role: arn:aws:iam::544471418261:role/opensearch-lambda-role

      Events:
        PdfUploadEvent:
          Type: S3
          Properties:
            Bucket: pdf-input-bkt   # existing bucket name
            Events:
              - s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: output/
                  - Name: suffix
                    Value: .txt